const EditAppointmentActionTypes = {
	EDIT_APPOINTMENT_START: "EDIT_APPOINTMENT_START",
	EDIT_APPOINTMENT_SUCCESS: "EDIT_APPOINTMENT_SUCCESS",
	EDIT_APPOINTMENT_FAILURE: "EDIT_APPOINTMENT_FAILURE",
	SET_EDITING_APPOINTMENT: "SET_EDITING_APPOINTMENT",
	CLEAR_EDITING_APPOINTMENT: "CLEAR_EDITING_APPOINTMENT",
};

export default EditAppointmentActionTypes;
