const UpcomingActionTypes = {
  FETCH_UPCOMING_APPOINTMENTS_START: "FETCH_UPCOMING_APPOINTMENTS_START",
  FETCH_UPCOMING_APPOINTMENTS_SUCCESS: "FETCH_UPCOMING_APPOINTMENTS_SUCCESS",
  FETCH_UPCOMING_APPOINTMENTS_FAILURE: "FETCH_UPCOMING_APPOINTMENTS_FAILURE",
};

export default UpcomingActionTypes;
