const AppointmentDataActionTypes = {
	FETCH_APPOINTMENT_START: "FETCH_APPOINTMENT_START",
	FETCH_APPOINTMENT_SUCCESS: "FETCH_APPOINTMENT_SUCCESS",
	FETCH_APPOINTMENT_FAILURE: "FETCH_APPOINTMENT_FAILURE",
	SET_LATEST_DOC: "SET_LATEST_DOC",
	SET_DATA_EMPTY: "SET_DATA_EMPTY",
	CLEAR_APPOINTMENT: "CLEAR_PROPERTIES",
};

export default AppointmentDataActionTypes;
